module.exports = {
    WAITING: null,
    ACTIVE: 0,
    SOLUTION_WORK_IN_PROGRESS: 1,
    SOLUTION_WAIT_TO_PROJECTS_END: 2,
    SOLUTION_FINISHED: 3,
    SOLUTION_FAILED: 4,
    PROJECT_WORK_IN_PROGRESS: 5,
    PROJECT_WAIT_FOR_TASKS_END: 6,
    PROJECT_FINISHED: 7,
    PROJECT_FAILED: 8,
    TASK_WAIT_TO_RUN: 9,
    TASK_RUNNING: 10,
    TASK_FINISHED: 11,
    TASK_FAILED: 12,
    FAILED: 13,
    WAIT_FOR_FILES_UPLOAD: 14
};
